import type { Metadata } from "next";
import { Pacifico, Fredoka } from "next/font/google";
import cn from "classnames";
import Providers from "./provider/provider";
import "./style/globals.css";

const pacifico = Pacifico({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--font-pacifico",
});

const fredoka = Fredoka({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "hackathon-nic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(fredoka.className, pacifico.variable)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
